config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'search#index'
  
  resources :products
  resources :signup do
    collection do
      get   'step0'
      get   'step1'
      post  'step2'
      post  'step3'
      post  'step4'
      post  'step5'
      post  'done' 
    end
  end

  resources :products_statuses, only: [:show, :destroy] do
    collection do
      post 'resume_sell'
      post 'pause_sell'
      get 'buy/:id' => 'products_statuses#buy', as: :buy
      get 'buy_confirm/:id' => 'products_statuses#buy_confirm', as: :buy_confirm
    end
  end

  get 'signup/show' => 'signup#show'

  get 'sell' => 'sell#new'
  get 'sell/edit/:id' => 'sell#edit', as: :sell_edit
  patch 'sell/edit/:id' => 'sell#update'

  resources :sell, only: [:create,:destroy] do
    collection do
      #Ajaxで動くアクションのルートを作成
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
      get 'get_method', defaults: { format: 'json' }
      get 'get_brand', defaults: { format: 'json' }  #brandモデルにメソッド記載
    end
  end

  resources :mypage, only: :index do
    collection do
      get    'profile'
      post   'profileUpdate'
      get    'card'
      get    'cardcreate'
      post   'cardAdd'
      delete 'cardDestroy'
      get    'logout'
      get    'identification'
      post   'identificationSave'
      
      resources :listings do
        get   'listing'
        get   'in_progress'
        get   'completed'
      end

      resources :items, only: :show do

      end

    end
  end
end

app/models/account_type.rb
class AccountType < ActiveHash::Base
  self.data = [
    {id: 1, name: '普通預金'}, {id: 2, name: '当座預金'}, {id: 3, name: '貯金預金'}
  ]
end

app/models/area.rb
class Area < ActiveHash::Base
  
  self.data = [
    {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
    {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
    {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
    {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
    {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
    {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
    {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
    {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
    {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
    {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
    {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
    {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
    {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
    {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
    {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
    {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
]

end

app/models/bank.rb
class Bank < ApplicationRecord
end

app/models/brand.rb
class Brand < ApplicationRecord

  def self.brand_search(search)
    return Brand.all() unless search
    Brand.where('name LIKE(?)', "%#{search}%")
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :products_status
  belongs_to :user
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :shipping_charge
  belongs_to :shipping_time
  belongs_to :shipping_method
  belongs_to :status
  belongs_to :sale_charge
  belongs_to :size
  belongs_to :category
  belongs_to :view_categories
  has_many   :products_statuses
  has_many   :product_images, dependent: :destroy
  accepts_nested_attributes_for :product_images
  
  # refer to active has github(https://github.com/zilkey/active_hash/blob/master/README.md)
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :area
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product, optional: true
  mount_uploader :url, ImageUploader
end

app/models/sale_charge.rb
class SaleCharge < ApplicationRecord
end

app/models/sale_order.rb
class SaleOrder < ApplicationRecord
end

app/models/shipping_time.rb
class ShippingTime < ApplicationRecord
end

app/models/size.rb
class Size < ApplicationRecord

end

app/models/sizes_category.rb
class SizesCategory < ApplicationRecord

 belongs_to :category
 belongs_to :size

end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/models/transfer_order.rb
class TransferOrder < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one     :transfer_address
  has_one     :payment_method
  has_many    :buyed_items, foreign_key: "buyer_id", class_name: "ProductsStatus"
  has_many    :selling_items, -> { where("buyer_id is NULL") }, foreign_key: "seller_id", class_name: "ProductsStatus"
  has_many    :sold_items, -> { where("buyer_id is not NULL") }, foreign_key: "seller_id", class_name: "ProductsStatus"
  has_many    :goods
  has_many    :products, through: :goods
  has_many    :sale_orders
  has_many    :transfer_orders
  has_many    :buyer_evaluations
  
  attr_writer :password_field
  attr_reader :password_field
  
  attr_writer :tell_number
  attr_reader :tell_number
  
  attr_writer :authorization_code
  attr_reader :authorization_code

end

app/models/view_category.rb
class ViewCategory < ApplicationRecord
  has_many :products
  has_ancestry
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  include CommonActions
  before_action :set_categories, only: :index

  def index
    # レディース
    @ladies_products = ProductsStatus.where(category_parent_id: 1, buyer_id: nil, selling_status: 0).order(created_at: :desc).limit(10)
    @ladies_products_images = base64image(@ladies_products)

    # メンズ
    @mens_products = ProductsStatus.where(category_parent_id: 219, buyer_id: nil, selling_status: 0).order(created_at: :desc).limit(10)
    @mens_products_images = base64image(@mens_products)
    
    # 家電・スマホ・カメラ
    @goods_products = ProductsStatus.where(category_parent_id: 983, buyer_id: nil, selling_status: 0).order(created_at: :desc).limit(10)
    @goods_products_images = base64image(@goods_products)
    
    # おもちゃ・ホビー・グッズ
    @toy_products = ProductsStatus.where(category_parent_id: 748, buyer_id: nil, selling_status: 0).order(created_at: :desc).limit(10)
    @toy_products_images = base64image(@toy_products)
    
    # ブランド
      # シャネル
    @chanel_products = ProductsStatus.where(brand_id: 2446, buyer_id: nil, selling_status: 0).order(created_at: :desc).limit(10)
    @chanel_products_images = base64image(@chanel_products)
    
    # ヴィトン
    @lv_products = ProductsStatus.where(brand_id: 6154, buyer_id: nil, selling_status: 0).order(created_at: :desc).limit(10)
    @lv_products_images = base64image(@lv_products)
  end


  def base64image(products)

    # product_imagse.urlをバイナリーデータにしてビューで表示できるようにする
    require 'base64'
    require 'aws-sdk'

    product_images_binary_datas = []

    if Rails.env.production?
      client = Aws::S3::Client.new(
                              region: 'ap-northeast-1',
                              access_key_id: Rails.application.secrets[:aws_access_key_id],
                              secret_access_key: Rails.application.secrets[:aws_secret_access_key],
                              )
      products.each do |product|
        binary_data = client.get_object(bucket: 'upload-freemarket', key: product.product.product_images[0].url.file.path).body.read
        product_images_binary_datas << Base64.strict_encode64(binary_data)
      end
      return product_images_binary_datas
    else
      products.each do |product|
        binary_data = File.read(product.product.product_images[0].url.file.file)
        product_images_binary_datas << Base64.strict_encode64(binary_data)
      end
      return product_images_binary_datas
    end

  end

end

app/views/search/_product.html.haml
= product.zip(image) do |product, image|
  %li.product__inner
    .product__content
      = link_to products_status_path(product.product.id), class: 'product__box', data:{turbolinks: false} do
        %figure.product__figure
          %figcaption
            %span.product__title
              = product.product.name
          .product__image__box
            .product__price
              = number_to_currency(product.product.price, :format => "%u%n", :unit => "￥")
            = image_tag "data:image/*;base64,#{image}", alt: 'product', class: 'product__image'

app/views/search/_top-page.html.haml
.page__container
  .page__box
    .slider-visual__container
      .swiper-container.top-carousel
        .swiper-wrapper
          .swiper-slide
            = image_tag 'top-banner_1.png', alt: 'swipe01'
          .swiper-slide
            = image_tag 'top-banner_2.jpg', alt: 'swipe02'
        .swiper-button-prev
        .swiper-button-next
        .swiper-pagination
    .spacer__container
      .spacr__inner
        %h2.spacer__title
          人気のカテゴリー
        .spacer__batch__box
          %ul.spacer__batch__inner
            %li.spacer__batch__block.cycle
              = link_to '#', class: 'spacer__batch__text' do
                レディース
            %li.spacer__batch__block.cycle
              = link_to '#', class: 'spacer__batch__text' do
                メンズ
            %li.spacer__batch__block.cycle
              = link_to '#', class: 'spacer__batch__text' do
                家電・スマホ・カメラ
            %li.spacer__batch__block.cycle
              = link_to '#', class: 'spacer__batch__text' do
                おもちゃ・ホビー・グッズ
    .main__continer
      .main__inner
        %h3.main__title
          レディース新着アイテム
        = link_to '#', class: 'more_link' do
          もっと見る
      .products__continer
        %ul.product__list
          = render partial: 'product',locals: {product: @ladies_products,image: @ladies_products_images}
      .main__inner
        %h3.main__title
          メンズ新着アイテム
      .products__continer
        %ul.product__list
          = render partial: 'product', locals: {product: @mens_products,image: @mens_products_images}
      .main__inner
        %h3.main__title
          家電・スマホ・カメラ 新着アイテム
      .products__continer
        %ul.product__list
          = render partial: 'product', locals: {product: @goods_products,image: @goods_products_images}
      .main__inner
        %h3.main__title
          おもちゃ・ホビー・グッズ 新着アイテム
      .products__continer
        %ul.product__list
          = render partial: 'product', locals: {product: @toy_products,image: @toy_products_images}
    .spacer__container
      .spacr__inner
        %h2.spacer__title
          人気のブランド
        .spacer__batch__box
          .spacer__batch__block.cycle
            .spacer__batch__text
              レディース
          .spacer__batch__block.cycle
            .spacer__batch__text
              ルイヴィトン
          .spacer__batch__block.cycle
            .spacer__batch__text
              シュプリーム
          .spacer__batch__block.cycle
            .spacer__batch__text
              ナイキ
    .main__continer
      .main__inner
        %h3.main__title
          シャネル新着アイテム
        = link_to '#', class: 'more_link' do
          もっと見る
      .products__continer
        %ul.product__list
          = render partial: 'product', locals: {product: @chanel_products,image: @chanel_products_images}
      .main__inner
        %h3.main__title
          ルイヴィトン新着アイテム
      .products__continer
        %ul.product__list
          = render partial: 'product', locals: {product: @lv_products,image: @lv_products_images}
  .product-btn__container
    = link_to 'sell', class: 'product-btn__link', data:{turbolinks: false} do
      .product-btn__innner
        .product-btn__text
          出品
        %i.fas.fa-camera-retro.product-btn__icon

app/views/search/index.html.haml
= render partial: 'common/global_header'
= render partial: 'top-page'
= render partial: 'common/global_pc_banner'
= render partial: 'common/global_footer'