config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'search#index'
  
  resources :products
  resources :signup do
    collection do
      get   'step0'
      get   'step1'
      post  'step2'
      post  'step3'
      post  'step4'
      post  'step5'
      post  'done' 
    end
  end

  resources :products_statuses, only: [:show, :destroy] do
    collection do
      post 'resume_sell'
      post 'pause_sell'
      get 'buy/:id' => 'products_statuses#buy', as: :buy
      get 'buy_confirm/:id' => 'products_statuses#buy_confirm', as: :buy_confirm
    end
  end

  get 'signup/show' => 'signup#show'

  get 'sell' => 'sell#new'
  get 'sell/edit/:id' => 'sell#edit', as: :sell_edit
  patch 'sell/edit/:id' => 'sell#update'

  resources :sell, only: [:create,:destroy] do
    collection do
      #Ajaxで動くアクションのルートを作成
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
      get 'get_method', defaults: { format: 'json' }
      get 'get_brand', defaults: { format: 'json' }  #brandモデルにメソッド記載
    end
  end

  resources :mypage, only: :index do
    collection do
      get    'profile'
      post   'profileUpdate'
      get    'card'
      get    'cardcreate'
      post   'cardAdd'
      delete 'cardDestroy'
      get    'logout'
      get    'identification'
      post   'identificationSave'
      
      resources :listings do
        get   'listing'
        get   'in_progress'
        get   'completed'
      end

      resources :items, only: :show do

      end

    end
  end
end

app/models/account_type.rb
class AccountType < ActiveHash::Base
  self.data = [
    {id: 1, name: '普通預金'}, {id: 2, name: '当座預金'}, {id: 3, name: '貯金預金'}
  ]
end

app/models/area.rb
class Area < ActiveHash::Base
  
  self.data = [
    {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
    {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
    {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
    {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
    {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
    {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
    {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
    {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
    {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
    {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
    {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
    {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
    {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
    {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
    {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
    {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
]

end

app/models/bank.rb
class Bank < ApplicationRecord
end

app/models/brand.rb
class Brand < ApplicationRecord

  def self.brand_search(search)
    return Brand.all() unless search
    Brand.where('name LIKE(?)', "%#{search}%")
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :products_status
  belongs_to :user
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :shipping_charge
  belongs_to :shipping_time
  belongs_to :shipping_method
  belongs_to :status
  belongs_to :sale_charge
  belongs_to :size
  belongs_to :category
  belongs_to :view_categories
  has_many   :products_statuses
  has_many   :product_images, dependent: :destroy
  accepts_nested_attributes_for :product_images
  
  # refer to active has github(https://github.com/zilkey/active_hash/blob/master/README.md)
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :area
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product, optional: true
  mount_uploader :url, ImageUploader
end

app/models/sale_charge.rb
class SaleCharge < ApplicationRecord
end

app/models/sale_order.rb
class SaleOrder < ApplicationRecord
end

app/models/shipping_time.rb
class ShippingTime < ApplicationRecord
end

app/models/size.rb
class Size < ApplicationRecord

end

app/models/sizes_category.rb
class SizesCategory < ApplicationRecord

 belongs_to :category
 belongs_to :size

end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/models/transfer_order.rb
class TransferOrder < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one     :transfer_address
  has_one     :payment_method
  has_many    :buyed_items, foreign_key: "buyer_id", class_name: "ProductsStatus"
  has_many    :selling_items, -> { where("buyer_id is NULL") }, foreign_key: "seller_id", class_name: "ProductsStatus"
  has_many    :sold_items, -> { where("buyer_id is not NULL") }, foreign_key: "seller_id", class_name: "ProductsStatus"
  has_many    :goods
  has_many    :products, through: :goods
  has_many    :sale_orders
  has_many    :transfer_orders
  has_many    :buyer_evaluations
  
  attr_writer :password_field
  attr_reader :password_field
  
  attr_writer :tell_number
  attr_reader :tell_number
  
  attr_writer :authorization_code
  attr_reader :authorization_code

end

app/models/view_category.rb
class ViewCategory < ApplicationRecord
  has_many :products
  has_ancestry
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController

  
  def step0
    @user = User.new
  end

  def step1
    @user = User.new
    session.delete(:user_id)
    session.delete(:step1)
    session.delete(:step4)
  end

  def step2
      session[:step1] = user_params_step1
      session[:step1].delete(:password_confirmation) 
      @user = User.new
  end
  
  def show
    @credit_card = PaymentMethod.new
  end

  def step3
    @tell_number = user_params_step2
    @user = User.new
  end

  def step4
    if user_params_step3 = '3333'
      user_params = session[:step1]
      user = User.create(user_params)
      sign_in user unless user_signed_in?
      session.delete(:step1)
      @user = User.new
    end
  end

  def step5
    session[:step4] = user_params_step4
    @credit_card = PaymentMethod.new
  end

  def done
    user = User.find(current_user.id)
    user.update(session[:step4])
    payment = PaymentMethod.new(user_params_step5)
    payment.save
    session.delete(:user_id)
    session.delete(:step4)
  end

  private
    def user_params_step1
      params.require(:user).permit(:nickname, :email, :password, :password_confirmation, :first_name, :last_name, :first_kananame, :last_kananame, :'birthday_date(1i)', :'birthday_date(2i)', :'birthday_date(3i)')
    end

    def user_params_step2
      params.require(:user).permit(:tell_number)
    end

    def user_params_step3
      params.require(:user).permit(:authorization_code)
    end

    def user_params_step4
      params.require(:user).permit(:address_first_name, :address_last_name, :address_firt_kananame, :address_last_kananame, :address_zipcode, :address_prefecture, :address_city, :address_block, :address_building, :address_phone_number)
    end

    def user_params_step5
      params.require(:payment_method).permit(:card_number, :'expiration_date(1i)', :'expiration_date(2i)', :'expiration_date(3i)', :secrity_code).merge(user_id: current_user.id)
    end
end

app/views/signup/_footer.html.haml
.footer
  .footer__box
    %li.footer__box__content
      %a{}プライバシーポリシー
    %li.footer__box__content
      %a{}メルカリ利用規約
    %li.footer__box__content
      %a{}特定商取引に関する表記
  .footer__box__img
    %img{}
  .footer__bottom
    ©️2019　Mercari

app/views/signup/done.html.haml
.single-container
  %header.single-header
    %h1.single-header__titele
      = link_to '/', class: "single-header__link" do
        = image_tag 'logo.svg', alt: 'logo', class: 'single-header__image'
    %nav.progress-bar.signup-bar
      %ol.clearfix
        %li
          会員情報
          .progress-status
        %li
          電話番号認証
          .progress-status
        %li
          お届け先住所入力
          .progress-status
        %li
          支払い方法
          .progress-status
        %li.active
          完了
          .progress-status
  %main.main-content
    .main-content__title
      %h2 登録完了
      .form__block__text__main
        ありがとうございました。
        %br/
        会員登録が完了しました。
      .form__actions
        .l-single-content
          = link_to '商品に戻る', root_path, class: 'btn-default btn-red'
  %footer.single-footer
    =render '/entry/entry-footer'

app/views/signup/show.html.haml
.single-container
  %header.single-header
    = render '/entry/entry-header'
    %nav.progress-bar.signup-bar
      %ol.clearfix
        %li
          会員情報
          .progress-status
        %li
          電話番号認証
          .progress-status
        %li
          お届け先住所入力
          .progress-status
        %li
          支払い方法
          .progress-status
        %li.active
          完了
          .progress-status
  %main.main-content
    .main-content__title
      %h2 登録完了
      .form__block__text__main
        ありがとうございました。
        %br/
        会員登録が完了しました。
      .form__actions
        .l-single-content
          = link_to '商品に戻る', root_path, class: 'btn-default btn-red'
  %footer.single-footer
    =render '/entry/entry-footer'

app/views/signup/step0.html.haml
.single-container
  %header.single-header
    =render '/entry/entry-header'
  %main.single-main
    %section.l-single-container
      - if user_signed_in?
        %h2.l-single-head.registration すでにログインしています
      - else
        %h2.l-single-head.registration 新規会員登録
        .l-single-inner.registration-form
          .l-single-content
            = link_to step1_signup_index_path, class: 'btn-default__login btn-red btn-mail' do
              %i.far.fa-envelope
                メールアドレスで登録する
            %button.btn-default__login.btn-facebook
              %i.fab.fa-facebook
                Facebookで登録する
            %button.btn-default__login.btn-sns-google
              Googleで登録する
  %footer.single-footer
    =render '/entry/entry-footer'

app/views/signup/step1.html.haml
.single-container
  %header.single-header
    %h1.single-header__titele
      = link_to '/', class: "single-header__link" do
        = image_tag 'logo.svg', alt: 'logo', class: 'single-header__image'
    %nav.progress-bar.signup-bar
      %ol.clearfix
        %li.active
          会員情報
          .progress-status
        %li
          電話番号認証
          .progress-status
        %li
          お届け先住所入力
          .progress-status
        %li
          支払い方法
          .progress-status
        %li
          完了
          .progress-status
  %main.main-content
    .main-content__title
      %h2 会員情報入力
    .main-content__form
      = form_for @user, url: step2_signup_index_path, html: {class: 'first-main__box'} do |f|
        .main-content__form__box
          .form__block
            = f.label :ニックネーム
            %span.form__block__required
              必須
            %br/
            = f.text_field :nickname, autofocus: true, placeholder: '例）メルカリ太郎', class: 'text_field', id: 'input-nickname'
          .form__block
            = f.label :メールアドレス
            %span.form__block__required
              必須
            %br/
            = f.email_field :email, placeholder: 'PC・携帯どちらでも可', class: 'text_field', id: 'input-email',type: 'email'
          .form__block
            = f.label :パスワード
            %span.form__block__required
              必須
            %br/
            = f.password_field :password, autocomplete: "new-password", placeholder: '7文字以上', class: 'text_field', id: 'input-password'
          .form__block
            = f.label :パスワード（確認）
            %span.form__block__required
              必須
            %br/
            =f.password_field :password_confirmation, placeholder: '7文字以上', class:'text_field', id: 'input-password_confirm'
          .form__block
            %h3.form__block__text
              本人確認
            .form__block__text__main
              安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
          .form__block#input-name
            = f.label :お名前（全角）
            %span.form__block__required
              必須
            %br/
            .form-separate
              = f.text_field :first_name, placeholder: '例）山田', class: 'text_field-half', id: 'input-first_name'
              = f.text_field :last_name, placeholder: '例）彩', class: 'text_field-half', id: 'input-last_name'
          .form__block#input-kananame
            = f.label :お名前（カナ）
            %span.form__block__required
              必須
            %br/
            .form-separate
              = f.text_field :first_kananame, placeholder: '例）ヤマダ', class: 'text_field-half', id: 'input-first_kananame'
              = f.text_field :last_kananame, placeholder: '例）アヤ', class: 'text_field-half', id: 'input-last_kananame'
          .form__block#input-birthday
            = f.label :生年月日
            %span.form__block__required
              必須
            %br/
            .birthday-select-wrap
              != sprintf(f.date_select(:birthday_date, use_month_numbers: true, include_blank: '%i.fas.fa-arrow-down', start_year: Time.now.year, end_year: (Time.now.year - 50), with_css_classes: 'XXXX', date_separator: '%s'), '年','月')+'日'
            .form-separate
            
          .form__block
            %p.form__block__info
              ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
          .main-content__bottom
            .g-recaptcha{"data-callback" => "clearcall", "data-sitekey" => "6Lc15q8UAAAAAIaFFQ7n3V-C1ZeVQoNqXAXpF0xn"}
            .text__consent
              「次へ進む」のボタンを押すことにより、
              %a{} 利用規約
              に同意したものとみなします
            .form__actions
              = f.submit "次へ進む", class: 'progress-btn btn-step1', data: { disable_with: 'Submitting...'}, disabled:true
            .text__right
              %a{} 本人情報の登録について
  =render '/entry/entry-footer'

app/views/signup/step2.html.haml
.single-container
  %header.single-header
    %h1.single-header__titele
      = link_to '/', class: "single-header__link" do
        = image_tag 'logo.svg', alt: 'logo', class: 'single-header__image'
    %nav.progress-bar.signup-bar
      %ol.clearfix
        %li
          会員情報
          .progress-status
        %li.active
          電話番号認証
          .progress-status
        %li
          お届け先住所入力
          .progress-status
        %li
          支払い方法
          .progress-status
        %li
          完了
          .progress-status
  %main.main-content
    .main-content__title
      %h2 電話番号の確認
    .main-content__form
      = form_for @user, url: step3_signup_index_path, html: {class: 'first-main__box'} do |f|
        .main-content__form__box
          .form__block
            = f.label :tell_number, '携帯電話の番号'
            %br/
            = f.text_field :tell_number, {class: 'fake-box', placeholder: '携帯電話の番号を入力', id: 'input-tel' }
          .form__block__text__main.phone
            本人確認のため、携帯電話のSNS(ショートメッセージサービス)を利用して認証を行います。
          .form__actions
            = f.submit "SMSを送信する", class: 'progress-btn btn-step2', disabled:true
          .form__block__text__main
            ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
          .text__right
            %a{} 電話番号の確認が必要な理由
  %footer.single-footer
    =render '/entry/entry-footer'

app/views/signup/step3.html.haml
.single-container
  %header.single-header
    %h1.single-header__titele
      = link_to '/', class: "single-header__link" do
        = image_tag 'logo.svg', alt: 'logo', class: 'single-header__image'
    %nav.progress-bar.signup-bar
      %ol.clearfix
        %li
          会員情報
          .progress-status
        %li.active
          電話番号認証
          .progress-status
        %li
          お届け先住所入力
          .progress-status
        %li
          支払い方法
          .progress-status
        %li
          完了
          .progress-status
  %main.main-content
    .main-content__title
      %h2 電話番号認証
    .main-content__form
      = form_for @user, url: step4_signup_index_path, html: {class: 'first-main__box'} do |f|
        .main-content__form__box
          .form__block
            = f.label :authorization_code, '認証番号'
            %br/
            = f.text_field :authorization_code, {class: 'fake-box', placeholder: '認証番号を入力', id: 'authorization_code' }
          .form__block__text__main.phone
            SNSで届いた認証番号を入力してください
          .form__actions
            = f.submit "認証して完了", class: 'progress-btn btn-step3', disabled:true
        .main-content__form__box.bottom
          .sub-content
            = form_for @user, url: step3_signup_index_path, method: :get, html: {class: 'first-main__box'} do |f|
              .attestation-number__error
                30秒たっても認証番号が届かないかたへ
              .attestation-number__message
                電話で認証番号を聞くこともできます
              .form__actions
                = f.submit "電話で認証番号を聞く（通話無料）", class: 'progress-btn'
          .sub-content
            .attestation-number__error
              認証番号を再送することもできます。もう一度電話番号を入力してください。
              .last-sentence
                %a{}電話番号を再度入力する
            .attestation-number__message
              ※SNSが届かない場合は
              %a{}SNS受信設定
              を確認して、もう一度入力してください。
  %footer.single-footer
    =render '/entry/entry-footer'

app/views/signup/step4.html.haml
.single-container
  %header.single-header
    %h1.single-header__titele
      = link_to '/', class: "single-header__link" do
        = image_tag 'logo.svg', alt: 'logo', class: 'single-header__image'
    %nav.progress-bar.signup-bar
      %ol.clearfix
        %li
          会員情報
          .progress-status
        %li
          電話番号認証
          .progress-status
        %li.active
          お届け先住所入力
          .progress-status
        %li
          支払い方法
          .progress-status
        %li
          完了
          .progress-status
  %main.main-content
    = form_for @user, url: step5_signup_index_path, html: {class: 'first-main__box'} do |f|
      .main-content__title
        %h2 発送元・お届け先住所入力
      .main-content__form
        .main-content__form__box
          .form__block#input-address_name
            = f.label :お名前
            %span.form__block__required
              必須
            %br/
            = f.text_field :address_first_name, class: 'text_field', placeholder: '例）山田', id: 'input-address_first_name'
            = f.text_field :address_last_name, class: 'text_field', placeholder: '例）綾', id: 'input-address_last_name'

          .form__block
            = f.label :お名前カナ
            %span.form__block__required
              必須
            %br/
            = f.text_field :address_firt_kananame, class: 'text_field', placeholder: '例）ヤマダ', id: 'input-address_firt_kananame'
            = f.text_field :address_last_kananame, class: 'text_field', placeholder: '例）アヤ', id: 'input-address_last_kananame'

          .form__block
            = f.label :郵便番号
            %span.form__block__required
              必須
            %br/
            = f.text_field :address_zipcode, class: 'text_field', placeholder:'例）123-4567', id: 'input-address_zipcode'
          .form__block
            = f.label :都道府県
            %span.form__block__required
              必須
            %br/
            = f.text_field :address_prefecture, class: 'text_field', placeholder: '例）横浜市緑区', id: 'input-address_prefecture'
          .form__block
            = f.label :市区村町
            %span.form__block__required
              必須
            %br/
            = f.text_field :address_city, class: 'text_field', placeholder: '例）横浜市緑区', id: 'input-address_city'
          .form__block
            = f.label :番町
            %span.form__block__required
              必須
            %br/
            = f.text_field :address_block, class: 'text_field', placeholder: '例）青山1-1-1', id: 'input-address_block'
          .form__block
            = f.label :建物名
            %span.form__block__discretion
              任意
            %br/
            = f.text_field :address_building, class: 'text_field', placeholder: '例）柳ビル103'
          .form__block
            = f.label :電話
            %span.form__block__discretion
              任意
            %br/
            = f.number_field :address_phone_number, class: 'text_field', placeholder: '例）09012345678'
          .form__actions
            = f.submit "次へ進む", class: 'progress-btn btn-step4', disabled:true
  %footer.single-footer
    =render '/entry/entry-footer'

app/views/signup/step5.html.haml
.single-container
  %header.single-header
    %h1.single-header__titele
      = link_to '/', class: "single-header__link" do
        = image_tag 'logo.svg', alt: 'logo', class: 'single-header__image'
    %nav.progress-bar.signup-bar
      %ol.clearfix
        %li
          会員情報
          .progress-status
        %li
          電話番号認証
          .progress-status
        %li
          お届け先住所入力
          .progress-status
        %li.active
          支払い方法
          .progress-status
        %li
          完了
          .progress-status
  %main.main-content
    .main-content__title
      %h2 支払い方法
    .main-content__form
      = form_for @credit_card, url: done_signup_index_path, html: {class: 'first-main__box'} do |f|
        = render partial: '/mypage/cardcreate_content', locals: { f: f } 
  %footer.single-footer
    =render '/entry/entry-footer'