config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'search#index'
  
  resources :products
  resources :signup do
    collection do
      get   'step0'
      get   'step1'
      post  'step2'
      post  'step3'
      post  'step4'
      post  'step5'
      post  'done' 
    end
  end

  resources :products_statuses, only: [:show, :destroy] do
    collection do
      post 'resume_sell'
      post 'pause_sell'
      get 'buy/:id' => 'products_statuses#buy', as: :buy
      get 'buy_confirm/:id' => 'products_statuses#buy_confirm', as: :buy_confirm
    end
  end

  get 'signup/show' => 'signup#show'

  get 'sell' => 'sell#new'
  get 'sell/edit/:id' => 'sell#edit', as: :sell_edit
  patch 'sell/edit/:id' => 'sell#update'

  resources :sell, only: [:create,:destroy] do
    collection do
      #Ajaxで動くアクションのルートを作成
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
      get 'get_method', defaults: { format: 'json' }
      get 'get_brand', defaults: { format: 'json' }  #brandモデルにメソッド記載
    end
  end

  resources :mypage, only: :index do
    collection do
      get    'profile'
      post   'profileUpdate'
      get    'card'
      get    'cardcreate'
      post   'cardAdd'
      delete 'cardDestroy'
      get    'logout'
      get    'identification'
      post   'identificationSave'
      
      resources :listings do
        get   'listing'
        get   'in_progress'
        get   'completed'
      end

      resources :items, only: :show do

      end

    end
  end
end

app/controllers/products_statuses_controller.rb
class ProductsStatusesController < ApplicationController
  include CommonActions
  before_action :authenticate_user!, only: [:buy]
  before_action :set_categories, only: [:index,:show]

  require 'date'

  def show
    # 製品情報
    @product_status = ProductsStatus.find(params[:id])
    # 製品画像
    @product_image = base64image(@product_status)

    # 製品名
    @product_name = @product_status.product.name

    # ユーザー情報
    @seller = User.find(@product_status.seller_id)
    @seller_name = @seller.nickname
    @good_count = @seller.buyer_evaluations.where(evaluation_id: 1).count
    @normal_count = @seller.buyer_evaluations.where(evaluation_id: 2).count
    @bad_count = @seller.buyer_evaluations.where(evaluation_id: 3).count

    # カテゴリ
    @large_category_name = ViewCategory.find_by(id: @product_status.product.category_parent_id).name
    @medium_category_name = ViewCategory.find_by(id: @product_status.product.category_children_id).name
    @smail_category_name = ViewCategory.find_by(id: @product_status.product.category_grandchild_id).name

    # ブランド
    brand_id = @product_status.product.brand
    if brand_id == ""
      @brand_name = ""
    else
      @brand_name = Brand.find(brand_id).name
    end

    # 商品サイズ
    @size_name = @product_status.product.size.name

    # 商品状態
    @status_name = @product_status.product.status.name

    # 配送料負担
    @shipping_charge_name = @product_status.product.shipping_charge.name

    # 配送方法
    @shipping_method_name = @product_status.product.shipping_method.name
    
    # 配送エリア
    area_id = @product_status.product.area_id
    @area = Area.all
    @area.each do |area|
      if area_id == area.id then
        @area_name = area.name
      end
    end

    # 発送までの目安
    time_id = @product_status.product.shipping_time_id
    @time = ShippingTime.all
    @time.each do |time|
      if time_id == time.id then
        @shipping_time_name = time.name
      end
    end
    # 価格
    @price = @product_status.product.price.to_s(:delimited)

    # 送料表示
    if @product_status.product.shipping_charge.id == 1
      @shipping_charge_name = "送料込み"
    elsif @product_status.product.shipping_charge.id == 2
      @shipping_charge_name = "着払い"
    end

    # 商品説明
    @description = @product_status.product.description

  end

  def resume_sell
  # 出品再開処理
    @product_status = ProductsStatus.find(params[:products_status][:product_id])
      @product_status.selling_status = 0  #出品中へ変更
    if @product_status.save
      flash[:notice] = '出品の再開をしました'
      redirect_to products_status_path(@product_status.id)
    else
      flash[:alert] = '該当の商品がみつかりませんでした'
      redirect_to root_path
    end
  end

  def pause_sell
  # 出品一時停止処理(公開停止)
    @product_status = ProductsStatus.find(params[:products_status][:product_id])
      @product_status.selling_status = 9  #一時停止へ変更
    if @product_status.save
      flash[:notice] = '出品の一時停止をしました'
      redirect_to products_status_path(@product_status.id)
    else
      flash[:alert] = '該当の商品がみつかりませんでした'
      redirect_to root_path
    end
  end

  def destroy
    @product_status = ProductsStatus.find(params[:id])
    if @product_status.destroy 
      flash[:notice] = '商品を削除しました'
      redirect_to root_path
    else
      flash[:alert] = '商品の削除ができませんでした'
      redirect_to root_path
    end
  end

  def buy
    # 製品情報
    @product_status = ProductsStatus.find(params[:id])
    # 製品画像
    @product_image = base64image(@product_status)
    # 製品名
    @product_name = @product_status.product.name
    # 価格
    @price = @product_status.product.price.to_s(:delimited)
    # 送料表示
    if @product_status.product.shipping_charge.id == 1
      @shipping_charge_name = "送料込み"
    elsif @product_status.product.shipping_charge.id == 2
      @shipping_charge_name = "着払い"
    end

    # 購入ユーザー情報
    @user = current_user
    if @user.payment_method
      @credit_card = @user.payment_method
      @credit_card_number = @credit_card.card_number.gsub(/\d(?=(\D*\d){4})/, '*')
      @credit_card_expiration_date_year = @credit_card.expiration_date.strftime("%Y")[-2,2]
      @credit_card_expiration_date_month = @credit_card.expiration_date.strftime("%m")
    end
    
    # 販売ユーザー情報
    @seller = User.find(@product_status.seller_id)
    @seller_name = @seller.nickname

    #jsへ渡すパラメーター
    gon.payment_method = @user.payment_method
    gon.user = @user
    gon.href = "/products_statuses/buy_confirm/#{params[:id]}"



  end

  def buy_confirm
    # 製品情報
    @product_status = ProductsStatus.find(params[:id])

    # 製品画像
    @product_image = base64image(@product_status)
    # 製品名
    @product_name = @product_status.product.name
    # 価格
    @price = @product_status.product.price.to_s(:delimited)
    # 送料表示
    if @product_status.product.shipping_charge.id == 1
      @shipping_charge_name = "送料込み"
    elsif @product_status.product.shipping_charge.id == 2
      @shipping_charge_name = "着払い"
    end
    
    @product_status = ProductsStatus.find(params[:id])
      @product_status.selling_status = 1  #SOLDへ変更
      @product_status.buyer_id = current_user.id
    unless @product_status.save
      flash[:alert] = '該当の商品がみつかりませんでした'
      redirect_to root_path
    end

  end


  def base64image(product)
    # product_imagse.urlをバイナリーデータにしてビューで表示できるようにする
    require 'base64'
    require 'aws-sdk'

    product_images_binary_datas = []

    if Rails.env.production?
      client = Aws::S3::Client.new(
                              region: 'ap-northeast-1',
                              access_key_id: Rails.application.secrets[:aws_access_key_id],
                              secret_access_key: Rails.application.secrets[:aws_secret_access_key],
                              )
      # product.each do |product|
      product.product.product_images.each_with_index do |product,i|
        binary_data = client.get_object(bucket: 'upload-freemarket', key: product.product.product_images[i].url.file.path).body.read
        product_images_binary_datas << Base64.strict_encode64(binary_data)
      end
      return product_images_binary_datas
    else
      product.product.product_images.each do |product|
        binary_data = File.read(product.url.file.file)
        product_images_binary_datas << Base64.strict_encode64(binary_data)
      end
      return product_images_binary_datas
    end
  end

end

app/views/products_statuses/_footer.html.haml
.footer
  .footer__top
    .footer__top__contaner
      .footer__top__contaner__left
        %h1 スマホでかんたんフリマアプリ
        %p 今すぐ無料ダウンロード！
        .footer__top__contaner__left__icon
          .footer__top__contaner__left__icon__mercari
            = image_tag '/images/custom-banner-icon.png'
          .footer__top__contaner__left__icon__link
            %ul
              %li
                = link_to '#' do
                  = image_tag '/images/app-store.png'
              %li
                = link_to '#' do
                  = image_tag '/images/google-play.png'
      .footer__top__contaner__right
        = image_tag '/images/download_content_pc.png' 

app/views/products_statuses/_header.html.haml
.header
  .header__top
    .header__top__icon
      = image_tag '/images/image.png', alt: '', height: '', width: '', class: ''
    %form.header__top__form{action: ''}
      %input{type: 'text', placeholder: '何かお探しですか？'}
  .header__bottome
    .header__bottome__left
      %ul
        %li 
          = link_to '#' do
            カテゴリーから探す
        %li
          = link_to '#' do
            ブランドから探す
    .header__bottome__right
      %ul
        %li.header__bottome__right--like
          = link_to '#' do
            いいね！一覧
        %li
          = link_to '#' do
            お知らせ
        %li
          = link_to '#' do
            やることリスト
        %li
          = link_to '#' do
            マイページ

app/views/products_statuses/_products_buy_confirm_content.html.haml
.main_product_buy_container
  .buy-product-container.l-single-container
    .buy-message
      .buy-message-main 発送をお待ち下さい
      .buy-message-content  出品者からの発送通知をお待ちください
    
    .buy-status
      %h2.buy-status-message  購入が完了しました

    .buy-content-main
      .buy-content-main-box
        .buy-content-main-box-image
          = image_tag "data:image/*;base64,#{@product_image[0]}",class:"confirm-image"
        .buy-content-main-box-detail
          %p.buy-content-main-box-name
            = @product_name
    
    .buy-confirm-pricebox
      %p.buy-confirm-pricebox-price
        %span
          = '¥' + @price
        = @shipping_charge_name

app/views/products_statuses/_products_buy_content.html.haml
.main_product_buy_container
  %section.buy-product-container.l-single-container
    %h2.l-single-head 購入内容の確認
    %section.buy-content.buy-product
      .buy-content-inner
        .buy-product-box
          %h3.buy-product-image
            = image_tag "data:image/*;base64,#{@product_image[0]}", class:"lazyloaded"
          .buy-product-detail
            %p.buy-product-name
              = @product_name
            %p.buy-price-ja.bold
              %span
                = '¥' + @price
              %span.product-shipping-fee
                = ' （税込）' + @shipping_charge_name

    %section.buy-content.buy-item
      .buy-content-inner
        = form_for @product_status ,class:"buy-form",method:"POST",novalidate:"novalidate" do |f|
          %ul.buy-price-table
            %li.buy-price-row.buy-you-pay.bold
              .buy-price-cell
                支払い金額
              .buy-price-cell
                %span
                  = '¥' + @price

            - if @credit_card
              %section.buy-content.buy-user-info
                .buy-content-inner
                  .clearfix
                    %h3.l-left 支払い方法
                    = link_to card_mypage_index_path,class:"buy-user-info-fix" do
                      変更する
                  %p.buy-user-info-text
                    クレジットカード
                    %br
                    = @credit_card_number
                    %br
                    = "有効期限 #{@credit_card_expiration_date_month +' / '+ @credit_card_expiration_date_year}"
                  %figure.buy-card-logo
                    = image_tag "/images/visa.svg", size: "32x20", alt: "jcb"
            - else
              %section.buy-content.buy-user-info
                .buy-content-inner
                  .clearfix
                    %h3.l-left 支払い方法
                  = link_to cardcreate_mypage_index_path do
                    .buy-user-info-text-link
                      登録してください


            - if @user.address_zipcode && @user.address_prefecture && @user.address_city && @user.address_block && @user.address_first_name && @user.address_last_name
              %section.buy-content.buy-user-info
                .buy-content-inner
                  .clearfix
                    %h3.l-left 配送先
                    = link_to '#',class:"buy-user-info-fix" do
                      変更する
                  %address.buy-user-info-text
                    = "〒#{@user.address_zipcode.to_s.insert(3, '-')}"
                    %br
                    = "#{@user.address_prefecture} #{@user.address_city} #{@user.address_block} #{@user.address_building}"
                    %br
                    = "#{@user.address_first_name + @user.address_last_name}"
                  %p.buy-user-info-text
            - else
              %section.buy-content.buy-user-info
                .buy-content-inner
                  .clearfix
                    %h3.l-left 配送先
                  = link_to '#' do
                    .buy-user-info-text-link
                      登録してください


            %section.buy-content.buy-user-info
              = link_to 'javascript:void(0)', class:"product-buy-btn", id:"buysubmitflag" do
                購入する

app/views/products_statuses/_products_statuses_content.html.haml
.main_container
  %section.product-box-container.ll-single-container
    %h1.product-name 
      = @product_name
    .product-main-content.clearfix
      .product-photo
        .owl-carousel.owl-loaded.owl-drag
          .owl-stage-outer
            .owl-stage{style:"left: 0px;"}
              - @product_image.each do |image|
                .owl-product{ style: 'width:300px'}
                  .owl-product-inner.is-higher-width
                    = image_tag "data:image/*;base64,#{image}",class: "owl-lazy",style:"opacity :1;"
          .owl-dots
            - @product_image.each do |image|
              .owl-dot
                .owl-dot-inner
                  = image_tag "data:image/*;base64,#{image}",class: "is-higher-width"

        - if @product_status.selling_status == 1
          .product-stop-badge_sold
            %div SOLD
        - if current_user
          - if current_user.id == @seller.id && @product_status.selling_status == 9
            .product-stop-badge_pause
              %div 公開停止中


      %table.product-detail-table
        %tbody
          %tr
            %th 出品者
            %td
              = link_to '#' do
                = @seller_name
              %div 
                .product-user-ratings
                  = icon("fas", "laugh",class: "icon-lauph")
                  %span
                  = @good_count
                .product-user-ratings
                  = icon("fas", "meh",class: "icon-meh")
                  %span
                  = @normal_count
                .product-user-ratings
                  = icon("fas", "frown",class: "icon-frown")
                  %span
                  = @bad_count
          %tr
            %th カテゴリー
            %td
              = link_to '#' do
                = @large_category_name
              = link_to '#' do
                .product-detail-table-sub-category
                  = icon("fas", "chevron-right")
                  = @medium_category_name
              = link_to '#' do
                .product-detail-table-sub-sub-category
                  = icon("fas", "chevron-right")
                  = @smail_category_name
          %tr
            %th ブランド
            %td
              = link_to '#' do
                = @brand_name
          %tr
            %th 商品のサイズ
            %td
              = @size_name
          %tr
            %th 商品の状態
            %td
              = @status_name
          %tr
            %th 配送料の負担
            %td
              = @shipping_charge_name
          %tr
            %th 配送の方法
            %td
              = @shipping_method_name
          %tr
            %th 配送元地域
            %td
              = @area_name
          %tr
            %th 発送日の目安
            %td
              = @shipping_time_name

    .product-price-box.text-center
      %span.product-price-box_price.bold
        ¥
        = @price
      %span.product-price-box_tax
        (税込)
      %span.product-price-box_shipping-fee
        = @shipping_charge_name

    - if current_user
      - if current_user.id != @seller.id && @product_status.selling_status == 0
        = link_to buy_products_statuses_path(@product_status.id), class:"product-buy-btn" do
          購入画面に進む
      - if current_user.id != @seller.id && @product_status.selling_status == 1
        %button.product-buy-btn-sold 売り切れました

    - else
      = link_to user_session_path, class:"product-buy-btn" do
        購入画面に進む


    .product-description.f14
      %p.product-description-inner
        = @description
      
      - if current_user == @seller.id
        .product-button-container.clearfix
          .product-button-left
            %button{class:"product-button product-button-like"}
              = icon("far fa-heart","heart",class:"icon-like")
              %span{class:"product-button-container span"} いいね！
            = link_to '#',class:"product-button product-button-report" do
              = icon("far fa-flag","flag")
              %span{class:"product-button-container span"} 不適切な商品の報告
          .product-button-right
            = link_to '#',class:"item-button-container a" do
              = icon("fas fa-lock","lock")
              %span{class:"product-button-container span"} あんしん・あんぜんへの取り組み

  - if current_user
    - if current_user.id == @seller.id
      .l-single-container
        .listing-product-change-box
          = link_to "商品の編集",sell_edit_path(@product_status.id), class:"btn-default btn-red"
          %p.text-center or
          - if @product_status.selling_status == 0
            = form_for(@product_status, url: pause_sell_products_statuses_path, method: :post) do |f|
              = f.hidden_field :product_id, value: @product_status.id
              = f.submit "出品を一旦停止する", class:"btn-default btn-gray"
          - elsif @product_status.selling_status == 9
            = form_for(@product_status, url: resume_sell_products_statuses_path, method: :post) do |f|
              = f.hidden_field :product_id, value: @product_status.id
              = f.submit "出品を再開する", class:"btn-default btn-red"
          %button#modal-open-btn.btn-default.btn-gray この商品を削除する
          = link_to "", "#{@product_status.id}",method: :delete, id:'item-delete-btn'
          #overlay
            #modalWindow
              .modal-message-box
                .modal-head.bold 確認
                %div 削除すると二度と復活できません。<br>削除する代わりに停止することもできます。<br><br>本当に削除しますか？
              %button#modal-close-btn キャンセル
              %button#delete-comformation-btn 削除する

      .product-detail-message
        .message-container
          .message-content
            %form{class:"message-form",method:"POST"}
              %p
                相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
              %textarea{type:"text",name:"body",class:"textarea-default"}
              %button{type:"submit",class:"message-submit btn-default btn-gray"}
                コメントする

    - else
      .product-detail-message
        .message-container
          /*.message-content
          /*message一覧表示*/
          .message-content
            %form{class:"message-form",method:"POST"}
              %p
                相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
              %textarea{type:"text",name:"body",class:"textarea-default"}
              %button{type:"submit",class:"message-submit btn-default btn-gray"}
                コメントする

  %ul.nav-product-link-prev-next.clearfix
    %li.nav-product-link-prev
      = link_to '#' do
        = icon("fas", "chevron-left")
        短期攻略センター 地学基礎
    %li.nav-product-link-next
      = link_to '#' do
        ポーチ【ハワイ限定】
        = icon("fas", "chevron-right")

  .product-social-media-box
    .text-center
    %ul.social-media-box
      %li
        = link_to '#' do
          = icon("fab fa-3x", "facebook-square",class:"icon-facebook")
      %li
        = link_to '#' do
          = icon("fab fa-3x", "twitter-square",class:"icon-twitter")
      %li
        = link_to '#' do
          = icon("fab fa-3x", "line",class:"icon-line")
      %li
        = link_to '#' do
          = icon("fab fa-3x", "pinterest-square",class:"icon-pinterest")
          
  
  .products-in-user-profile
    //この出品者の他の商品を表示

app/views/products_statuses/buy.html.haml
-# gemの「gon」を読み込み
= include_gon

= render partial: 'entry/entry-header'
= render partial: 'products_buy_content'
= render partial: 'entry/entry-footer'

app/views/products_statuses/buy_confirm.html.haml
= render partial: 'entry/entry-header'
= render partial: 'products_buy_confirm_content'
= render partial: 'entry/entry-footer'

app/views/products_statuses/index.html.haml
= render partial: 'common/global_header'
%nav.bread-crumbs
%main.l-container.clearfix
  = render partial: 'products_statuses_content'
= render partial: 'common/global_pc_banner'
= render partial: 'common/global_footer'

app/views/products_statuses/show.html.haml
= render partial: 'common/global_header'
%nav.bread-crumbs

/* CDN : slick(スライダー用) */
%link{rel: "stylesheet", type:"text/css", href: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"}
%script{type: "text/javascript", src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"}

%main.l-container.clearfix
  = render partial: 'products_statuses_content'
= render partial: 'common/global_pc_banner'
= render partial: 'common/global_footer'