config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'search#index'
  
  resources :products
  resources :signup do
    collection do
      get   'step0'
      get   'step1'
      post  'step2'
      post  'step3'
      post  'step4'
      post  'step5'
      post  'done' 
    end
  end

  resources :products_statuses, only: [:show, :destroy] do
    collection do
      post 'resume_sell'
      post 'pause_sell'
      get 'buy/:id' => 'products_statuses#buy', as: :buy
      get 'buy_confirm/:id' => 'products_statuses#buy_confirm', as: :buy_confirm
    end
  end

  get 'signup/show' => 'signup#show'

  get 'sell' => 'sell#new'
  get 'sell/edit/:id' => 'sell#edit', as: :sell_edit
  patch 'sell/edit/:id' => 'sell#update'

  resources :sell, only: [:create,:destroy] do
    collection do
      #Ajaxで動くアクションのルートを作成
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_size', defaults: { format: 'json' }
      get 'get_method', defaults: { format: 'json' }
      get 'get_brand', defaults: { format: 'json' }  #brandモデルにメソッド記載
    end
  end

  resources :mypage, only: :index do
    collection do
      get    'profile'
      post   'profileUpdate'
      get    'card'
      get    'cardcreate'
      post   'cardAdd'
      delete 'cardDestroy'
      get    'logout'
      get    'identification'
      post   'identificationSave'
      
      resources :listings do
        get   'listing'
        get   'in_progress'
        get   'completed'
      end

      resources :items, only: :show do

      end

    end
  end
end

app/models/account_type.rb
class AccountType < ActiveHash::Base
  self.data = [
    {id: 1, name: '普通預金'}, {id: 2, name: '当座預金'}, {id: 3, name: '貯金預金'}
  ]
end

app/models/area.rb
class Area < ActiveHash::Base
  
  self.data = [
    {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
    {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
    {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
    {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
    {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
    {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
    {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
    {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
    {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
    {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
    {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
    {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
    {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
    {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
    {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
    {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
]

end

app/models/bank.rb
class Bank < ApplicationRecord
end

app/models/brand.rb
class Brand < ApplicationRecord

  def self.brand_search(search)
    return Brand.all() unless search
    Brand.where('name LIKE(?)', "%#{search}%")
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :products_status
  belongs_to :user
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :shipping_charge
  belongs_to :shipping_time
  belongs_to :shipping_method
  belongs_to :status
  belongs_to :sale_charge
  belongs_to :size
  belongs_to :category
  belongs_to :view_categories
  has_many   :products_statuses
  has_many   :product_images, dependent: :destroy
  accepts_nested_attributes_for :product_images
  
  # refer to active has github(https://github.com/zilkey/active_hash/blob/master/README.md)
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :area
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product, optional: true
  mount_uploader :url, ImageUploader
end

app/models/sale_charge.rb
class SaleCharge < ApplicationRecord
end

app/models/sale_order.rb
class SaleOrder < ApplicationRecord
end

app/models/shipping_time.rb
class ShippingTime < ApplicationRecord
end

app/models/size.rb
class Size < ApplicationRecord

end

app/models/sizes_category.rb
class SizesCategory < ApplicationRecord

 belongs_to :category
 belongs_to :size

end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/models/transfer_order.rb
class TransferOrder < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one     :transfer_address
  has_one     :payment_method
  has_many    :buyed_items, foreign_key: "buyer_id", class_name: "ProductsStatus"
  has_many    :selling_items, -> { where("buyer_id is NULL") }, foreign_key: "seller_id", class_name: "ProductsStatus"
  has_many    :sold_items, -> { where("buyer_id is not NULL") }, foreign_key: "seller_id", class_name: "ProductsStatus"
  has_many    :goods
  has_many    :products, through: :goods
  has_many    :sale_orders
  has_many    :transfer_orders
  has_many    :buyer_evaluations
  
  attr_writer :password_field
  attr_reader :password_field
  
  attr_writer :tell_number
  attr_reader :tell_number
  
  attr_writer :authorization_code
  attr_reader :authorization_code

end

app/models/view_category.rb
class ViewCategory < ApplicationRecord
  has_many :products
  has_ancestry
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  include CommonActions
  before_action :set_categories, except:[:cardDestroy, :cardAdd, :profileUpdate]
  before_action :authenticate_user!, except: :index
  
  def index
    @user = current_user
    @evaluation_count = @user.buyer_evaluations.count
    @products_count = ProductsStatus.where(buyer_id: @user.id).count
  end

  def card
    @user = current_user
    @credit_card = @user.payment_method
    
    unless @credit_card.nil?
      reg = Regexp.new(@credit_card.card_number);
      @credit_card_last4 = (@credit_card.card_number.to_i % 10000).to_s
    end
  end

  def cardDestroy
    credit_card = PaymentMethod.find(paymentMethodId[:id])
    credit_card.destroy
    redirect_to card_mypage_index_path, notice:'クレジットカード情報を削除しました!'
  end
  
  def cardcreate
    @user = current_user
    @credit_card = PaymentMethod.new
  end

  def cardAdd
    @credit_card = PaymentMethod.new(creditParam)
    @credit_card.user_id = current_user.id

    if @credit_card.save
      redirect_to card_mypage_index_path, notice:'クレジットカードを追加しました!'
    else
      flash.now[:alert] = '既に同じカードが存在するため登録できません'
      render :card
    end
  end
 
  def logout
    @user = current_user if user_signed_in?
  end

  def profile
    @user = current_user
  end

  def profileUpdate
    @user = current_user
    if @user.update_attributes(userProfile)
      redirect_to profile_mypage_index_path, notice:'変更しました!!'
    else
      flash.now[:alert] = 'もう一度入力して下さい。'
      render :index
    end
  end
  
  def identification
    @user = current_user
  end

  def identificationSave
    @user = current_user
    if @user.update_attributes(setIndentification)
      redirect_to identification_mypage_index_path, notice:'変更しました!!'      
    else
      flash.now[:alert] = 'もう一度入力して下さい。'
      render :identification
    end
  end

  private
  def userProfile
    params.permit(:nickname, :profiletext)
  end

  def creditParam
    params.require(:payment_method).permit(:user_id, :card_number, :expiration_date, :secrity_code)
  end
  
  def paymentMethodId
    params.require(:payment_method).permit(:id)
  end

  def setIndentification
    params.require(:user).permit(:address_zipcode, :address_prefecture, :address_city, :address_block, :address_building)
  end

end

app/views/mypage/_card_content.html.haml
.l-content
  %section.l-chapter-container
    %h2.l-chapter-head
      支払い方法
    .l-single-inner
      %section
        .l-single-content
          %h3.l-chapter-sub-head クレジットカード一覧
      %section.settings-add-card
        .l-single-content
          - if @credit_card.nil?
            = link_to cardcreate_mypage_index_path, class: 'btn-default btn-red submit_button', method: :get, params: { id: @user.id } do
              %i.far.fa-credit-card
                クレジットカードを追加する
          - else
            %ul.settings-payment-list
              %li
                = form_for @credit_card, url: cardDestroy_mypage_index_path, html: {method: :delete, class: 'l-single-content'} do |f|
                  %figure
                    %img{ alt: "", src: "/images/visa.svg", height: "60", width: "60"}
                  .settings-payment-num
                    = f.hidden_field :id, value: @credit_card.id
                    = "************ " + @credit_card_last4
                  .settings-payment-num
                    = @credit_card.expiration_date.strftime("%m") + '/' +  @credit_card.expiration_date.strftime("%y") 
                  = f.submit "削除する", class: 'settings-payment-remove'
                    
      .settings-not-regist
        = link_to '#', target: '_blank' do
          %span 支払い方法について
          %i.fas.fa-arrow-circle-right

app/views/mypage/_card_sideber.html.haml
.l-side
  %nav.mypage-nav
    %ul.mypage-nav-list
      %li
        = link_to mypage_index_path, class: 'mypage-nav-list-item' do
          マイページ
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          やることリスト
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          いいね!一覧
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          出品する
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          出品した商品-出品中
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          出品した商品-取引中
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          購入した商品-取引中
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          購入した商品-過去の取引
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          ニュース一覧
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          評価一覧
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          ガイド
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          お問い合わせ
          %i.fas.fa-angle-double-right
    %h3.mypage-nav-head
      メルペイ
    %ul.mypage-nav-list
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          売上・振込申請
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          ポイント
          %i.fas.fa-angle-double-right
    %h3.mypage-nav-head
      設定
    %ul.mypage-nav-list
      %li
        = link_to profile_mypage_index_path, class: 'mypage-nav-list-item' do
          プロフィール
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          発送元・お届け先住所変更
          %i.fas.fa-angle-double-right
      %li
        = link_to card_mypage_index_path, class: 'mypage-nav-list-item active' do
          支払い方法
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          メール/パスワード
          %i.fas.fa-angle-double-right
      %li
        = link_to identification_mypage_index_path, class: 'mypage-nav-list-item' do
          本人情報
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          電話番号の確認
          %i.fas.fa-angle-double-right
      %li
        = link_to logout_mypage_index_path, class: 'mypage-nav-list-item' do
          ログアウト
          %i.fas.fa-angle-double-right

app/views/mypage/_footer.html.haml
.footer
  .footer__top
    .footer__top__contaner
      .footer__top__contaner__left
        %h1 スマホでかんたんフリマアプリ
        %p 今すぐ無料ダウンロード！
        .footer__top__contaner__left__icon
          .footer__top__contaner__left__icon__mercari
            = image_tag '/images/custom-banner-icon.png'
          .footer__top__contaner__left__icon__link
            %ul
              %li
                %a{href: ''}
                  = image_tag '/images/app-store.png'
              %li
                %a{href: ''}
                  = image_tag '/images/google-play.png'
      .footer__top__contaner__right
        = image_tag '/images/download_content_pc.png' 

app/views/mypage/_header.html.haml
.header
  .header__top
    .header__top__icon
      = image_tag '/images/image.png', alt: '', height: '', width: '', class: ''
    %form.header__top__form{action: ''}
      %input{type: 'text', placeholder: '何かお探しですか？'}
  .header__bottome
    .header__bottome__left
      %ul
        %li 
          カテゴリーから探す
          %a{href: ''}
        %li
          ブランドから探す
          %a{href: ''}
    .header__bottome__right
      %ul
        %li.header__bottome__right--like
          いいね！一覧
          %a{href: ''}
        %li
          お知らせ
          %a{href: ''}
        %li
          やることリスト
          %a{href: ''}
        %li
          マイページ
          %a{href: ''}

app/views/mypage/_identification_sideber.html.haml
.l-side
  %nav.mypage-nav
    %ul.mypage-nav-list
      %li
        = link_to mypage_index_path, class: 'mypage-nav-list-item' do
          マイページ
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          やることリスト
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          いいね!一覧
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          出品する
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          出品した商品-出品中
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          出品した商品-取引中
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          購入した商品-取引中
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          購入した商品-過去の取引
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          ニュース一覧
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          評価一覧
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          ガイド
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          お問い合わせ
          %i.fas.fa-angle-double-right
    %h3.mypage-nav-head
      メルペイ
    %ul.mypage-nav-list
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          売上・振込申請
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          ポイント
          %i.fas.fa-angle-double-right
    %h3.mypage-nav-head
      設定
    %ul.mypage-nav-list
      %li
        = link_to profile_mypage_index_path, class: 'mypage-nav-list-item' do
          プロフィール
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          発送元・お届け先住所変更
          %i.fas.fa-angle-double-right
      %li
        = link_to card_mypage_index_path, class: 'mypage-nav-list-item' do
          支払い方法
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          メール/パスワード
          %i.fas.fa-angle-double-right
      %li
        = link_to identification_mypage_index_path, class: 'mypage-nav-list-item active' do
          本人情報
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          電話番号の確認
          %i.fas.fa-angle-double-right
      %li
        = link_to logout_mypage_index_path, class: 'mypage-nav-list-item' do
          ログアウト
          %i.fas.fa-angle-double-right

app/views/mypage/_profile_content.html.haml
.l-content
  %section.l-chapter-container
    %h2.l-chapter-head
      プロフィール
    = form_for(@user, url: profileUpdate_mypage_index_path, method: "post") do |f|
      .setting-profile-icon
        %figure
          %img{ alt: "", src: "/images/member_photo_noimage_thumb.png", height: "60", width: "60"}
        %input{ name: "nickname", type: "text", placeholder: "例)AYA☆セール中", value: @user.nickname, class: 'profile-input-default'}
      .setting-profile-content
        %textarea{ name: 'profiletext', value: '', class: 'textarea-default', placeholder: '例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪' }
          = @user.profiletext
        %input{ name: 'after_save_callback', type: 'hidden', value: profileUpdate_mypage_index_path } 
        %input{ name: 'id', type: 'hidden', value: @user.id } 
        %button{ type: 'submit', class: 'btn-default btn-red' }変更する

app/views/mypage/_profile_sideber.html.haml
.l-side
  %nav.mypage-nav
    %ul.mypage-nav-list
      %li
        = link_to mypage_index_path, class: 'mypage-nav-list-item' do
          マイページ
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          やることリスト
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          いいね!一覧
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          出品する
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          出品した商品-出品中
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          出品した商品-取引中
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          購入した商品-取引中
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          購入した商品-過去の取引
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          ニュース一覧
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          評価一覧
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          ガイド
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          お問い合わせ
          %i.fas.fa-angle-double-right
    %h3.mypage-nav-head
      メルペイ
    %ul.mypage-nav-list
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          売上・振込申請
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          ポイント
          %i.fas.fa-angle-double-right
    %h3.mypage-nav-head
      設定
    %ul.mypage-nav-list
      %li
        = link_to profile_mypage_index_path, class: 'mypage-nav-list-item active' do
          プロフィール
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          発送元・お届け先住所変更
          %i.fas.fa-angle-double-right
      %li
        = link_to card_mypage_index_path, class: 'mypage-nav-list-item' do
          支払い方法
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          メール/パスワード
          %i.fas.fa-angle-double-right
      %li
        = link_to identification_mypage_index_path, class: 'mypage-nav-list-item' do
          本人情報
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          電話番号の確認
          %i.fas.fa-angle-double-right
      %li
        = link_to logout_mypage_index_path, class: 'mypage-nav-list-item' do
          ログアウト
          %i.fas.fa-angle-double-right

app/views/mypage/_sideber.html.haml
.l-side
  %nav.mypage-nav
    %ul.mypage-nav-list
      %li
        = link_to mypage_index_path, class: 'mypage-nav-list-item active' do
          マイページ
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          やることリスト
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          いいね!一覧
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          出品する
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          出品した商品-出品中
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          出品した商品-取引中
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          購入した商品-取引中
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          購入した商品-過去の取引
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          ニュース一覧
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          評価一覧
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          ガイド
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          お問い合わせ
          %i.fas.fa-angle-double-right
    %h3.mypage-nav-head
      メルペイ
    %ul.mypage-nav-list
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          売上・振込申請
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          ポイント
          %i.fas.fa-angle-double-right
    %h3.mypage-nav-head
      設定
    %ul.mypage-nav-list
      %li
        = link_to profile_mypage_index_path, class: 'mypage-nav-list-item' do
          プロフィール
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          発送元・お届け先住所変更
          %i.fas.fa-angle-double-right
      %li
        = link_to card_mypage_index_path, class: 'mypage-nav-list-item' do
          支払い方法
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          メール/パスワード
          %i.fas.fa-angle-double-right
      %li
        = link_to identification_mypage_index_path, class: 'mypage-nav-list-item' do
          本人情報
          %i.fas.fa-angle-double-right
      %li
        = link_to '#', class: 'mypage-nav-list-item' do
          電話番号の確認
          %i.fas.fa-angle-double-right
      %li
        = link_to logout_mypage_index_path, class: 'mypage-nav-list-item' do
          ログアウト
          %i.fas.fa-angle-double-right

app/views/mypage/card.html.haml
= render partial: 'common/global_header'

- breadcrumb :card
= render "layouts/breadcrumbs"

%nav.bread-crumbs
%main.l-container.clearfix
  = render partial: 'card_content'
  = render partial: 'card_sideber'
= render partial: 'common/global_pc_banner'
= render partial: 'common/global_footer'

app/views/mypage/cardcreate.html.haml
= render partial: 'common/global_header'
%nav.bread-crumbs
%main.l-container.clearfix
  .l-content
    %section.l-chapter-container
      %h2.l-chapter-head クレジットカード情報入力
      = form_for @credit_card, url: cardAdd_mypage_index_path, html: {class: 'l-single-inner registration-form'} do |f|
        = render partial: 'cardcreate_content', locals: { user: @user, credit_card: @credit_card, f: f } 
  = render partial: 'card_sideber'
= render partial: 'common/global_pc_banner'
= render partial: 'common/global_footer'

app/views/mypage/index.html.haml
= render partial: 'common/global_header'

- breadcrumb :mypage
= render "layouts/breadcrumbs"

%nav.bread-crumbs
%main.l-container.clearfix
  = render partial: 'mypage_content'
  = render partial: 'sideber'
= render partial: 'common/global_pc_banner'
= render partial: 'common/global_footer'

app/views/mypage/logout.html.haml
= render partial: 'common/global_header'

- breadcrumb :logout
= render "layouts/breadcrumbs"

%nav.bread-crumbs
%main.l-container.clearfix
  .l-content
    .l-chapter-container
      .l-single-inner
        .l-single-content
          = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'btn-default btn-red'        
  = render partial: 'sideber'
= render partial: 'common/global_pc_banner'
= render partial: 'common/global_footer'

app/views/mypage/profile.html.haml
= render partial: 'common/global_header'

- breadcrumb :profile
= render "layouts/breadcrumbs"

%nav.bread-crumbs
%main.l-container.clearfix
  = render partial: 'profile_content'
  = render partial: 'profile_sideber'
= render partial: 'common/global_pc_banner'
= render partial: 'common/global_footer'